# -*- coding: utf-8 -*-
"""finalproject_task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1feA_NjGCvsNtI5RnYqrYVJVRKRmWkkEC
"""

!pip install ultralytics opencv-python-headless shapely

from google.colab import files

# Upload the video file
uploaded = files.upload()

import cv2
import numpy as np
from ultralytics import YOLO
from shapely.geometry import Point, Polygon

model = YOLO("yolov8n.pt")

cap = cv2.VideoCapture("dashcam.mp4")

width  = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps    = int(cap.get(cv2.CAP_PROP_FPS))


# ROI Definition (Trapezoid)

roi_points = np.array([
    (width * 0.3, height * 0.6),
    (width * 0.7, height * 0.6),
    (width * 0.95, height * 0.95),
    (width * 0.05, height * 0.95)
], np.int32)

roi_polygon = Polygon(roi_points)

# Vehicle Tracking for Counting

vehicle_id = 0
tracked_vehicles = {}
counted_ids = set()
vehicle_count = 0


# Lane Detection Functions

def region_of_interest(img):
    mask = np.zeros_like(img)
    cv2.fillPoly(mask, [roi_points], 255)
    return cv2.bitwise_and(img, mask)

def average_lane(lines):
    left, right = [], []
    for line in lines:
        x1,y1,x2,y2 = line[0]
        slope = (y2-y1)/(x2-x1+1e-6)
        if slope < -0.5:
            left.append(line[0])
        elif slope > 0.5:
            right.append(line[0])
    return left, right

def make_line(img, line_set):
    if len(line_set) == 0:
        return None
    x = []
    y = []
    for x1,y1,x2,y2 in line_set:
        x.extend([x1,x2])
        y.extend([y1,y2])
    poly = np.polyfit(y, x, 1)
    y1 = img.shape[0]
    y2 = int(img.shape[0]*0.6)
    x1 = int(poly[0]*y1 + poly[1])
    x2 = int(poly[0]*y2 + poly[1])
    return (x1,y1,x2,y2)


# Output Video

fourcc = cv2.VideoWriter_fourcc(*'mp4v')
out = cv2.VideoWriter("ADAS_output.mp4", fourcc, fps, (width, height))

# Main Loop

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    overlay = frame.copy()


    # LANE DETECTION

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    blur = cv2.GaussianBlur(gray,(5,5),0)
    edges = cv2.Canny(blur,50,150)
    masked_edges = region_of_interest(edges)

    lines = cv2.HoughLinesP(masked_edges,1,np.pi/180,50,minLineLength=50,maxLineGap=150)

    lane_center_x = width // 2
    if lines is not None:
        left,right = average_lane(lines)
        left_line  = make_line(frame,left)
        right_line = make_line(frame,right)

        if left_line and right_line:
            cv2.line(overlay,left_line[:2],left_line[2:],(0,255,0),5)
            cv2.line(overlay,right_line[:2],right_line[2:],(0,255,0),5)

            lane_center_x = (left_line[0] + right_line[0]) // 2
            cv2.line(overlay,(lane_center_x,height),(lane_center_x,int(height*0.6)),(255,0,0),3)

            lane_area = np.array([
                (left_line[0],left_line[1]),
                (left_line[2],left_line[3]),
                (right_line[2],right_line[3]),
                (right_line[0],right_line[1])
            ])
            cv2.fillPoly(overlay,[lane_area],(0,255,0))

    # Lane Departure
    car_center = width // 2
    offset = abs(car_center - lane_center_x)
    if offset > 60:
        cv2.putText(overlay,"LANE DEPARTURE WARNING",(50,80),
                    cv2.FONT_HERSHEY_SIMPLEX,1,(0,0,255),3)


    # VEHICLE DETECTION (YOLO)

    results = model(frame, conf=0.4, classes=[2,3,5,7], verbose=False)[0]

    for box in results.boxes:
        x1,y1,x2,y2 = map(int,box.xyxy[0])
        conf = float(box.conf[0])
        cx,cy = (x1+x2)//2,(y1+y2)//2

        point = Point(cx,cy)

        # ROI check
        if roi_polygon.contains(point):
            # Vehicle counting
            new_vehicle = True
            for vid,(px,py) in tracked_vehicles.items():
                if abs(cx-px)<40 and abs(cy-py)<40:
                    new_vehicle = False
                    tracked_vehicles[vid] = (cx,cy)
                    break

            if new_vehicle:
                vehicle_id += 1
                tracked_vehicles[vehicle_id] = (cx,cy)
                if vehicle_id not in counted_ids:
                    counted_ids.add(vehicle_id)
                    vehicle_count += 1

            # Collision Risk
            box_area = (x2-x1)*(y2-y1)
            if box_area > 40000 or y2 > height*0.85:
                cv2.putText(overlay,"COLLISION RISK",(x1,y1-10),
                            cv2.FONT_HERSHEY_SIMPLEX,0.8,(0,0,255),2)

            cv2.rectangle(overlay,(x1,y1),(x2,y2),(255,0,0),2)
            cv2.putText(overlay,f"{conf:.2f}",(x1,y2+20),
                        cv2.FONT_HERSHEY_SIMPLEX,0.6,(255,255,255),2)

    # ROI Visualization
    cv2.polylines(overlay,[roi_points],True,(255,255,0),3)

    # Vehicle Count
    cv2.putText(overlay,f"Vehicle Count: {vehicle_count}",
                (50,50),cv2.FONT_HERSHEY_SIMPLEX,1,(255,255,255),3)

    # Blend
    final = cv2.addWeighted(frame,0.4,overlay,0.6,0)
    out.write(final)

cap.release()
out.release()

from google.colab import files

files.download("ADAS_output.mp4")