# -*- coding: utf-8 -*-
"""task1,2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ocfchqLo6Nz5Gm7K40_gNRDAgImXGDM-
"""

import cv2 as cv
import numpy as np
from google.colab.patches import cv2_imshow
from google.colab import files
uploaded = files.upload()
img = cv.imread('road1.png')
cv2_imshow(img)
img_gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY )
img_blur1 = cv.blur(img_gray,(5,5))
cv2_imshow(img_blur1)
img_blur2 = cv.blur(img_gray,(15,15))
cv2_imshow(img_blur2)

import cv2 as cv
import numpy as np
from google.colab.patches import cv2_imshow
from google.colab import files
uploaded = files.upload()
img = cv.imread('road1.png')
img_gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
edges1 = cv.Canny(img_gray, 50, 150)
cv2_imshow(edges1)

edges2 = cv.Canny(img_gray, 10, 100 )
cv2_imshow(edges2)

import numpy as np
import cv2 as cv
import matplotlib.pyplot as plt
from google.colab.patches import cv2_imshow
from google.colab import files
uploaded = files.upload()

#capturing the video
cap = cv.VideoCapture('roadvideo.mp4')
if not cap.isOpened():
  print("cannot open camera")
  exit()

#creating empty list to store all the frames we want to display
frames = []
edge_frames = []
frame_gap = 20
num_frames = 5
frames_id = 0
while True:
    ret, frame = cap.read()
    if not ret:
      break

    if frames_id%frame_gap ==0:

      gray = cv.cvtColor(frame, cv.COLOR_BGR2GRAY)
      edges = cv.Canny(gray, 50, 150)
      frames.append(frame)
      edge_frames.append(edges)
      if len(frames) == num_frames:
       break
    frames_id +=1

cap.release()

#plotting the pictures side by side using matplotlib
plt.figure(figsize=(15, 3 *num_frames))

for i in range(num_frames):
    #original frame on the left side

 plt.subplot(num_frames , 2 , 2*i+1)
 plt.imshow(cv.cvtColor(frames[i],cv.COLOR_BGR2RGB))
 plt.axis('off')

    #the edge detected frame on the right side
 plt.subplot(num_frames , 2 , 2*i+2)
 plt.imshow(edge_frames[i],cmap = 'gray')
 plt.axis('off')

plt.show()